const SERVER_IP = import.meta.env.VITE_DEV_AUTH_URL;
const SERVER_BUSINESS_IP = import.meta.env.VITE_DEV_BUS_URL;
const SERVER_INVENTORY_IP = import.meta.env.VITE_DEV_INVEN_URL;
const AUTH_ROUTE = import.meta.env.VITE_AUTH_ROUTE;
const INVENTORY_ROUTE = import.meta.env.VITE_INVENTORY_ROUTE;
const ROUTE_USERS = import.meta.env.VITE_USERS_ROUTE;
const ROUTE_UTILITIES = import.meta.env.VITE_UTILITIES_ROUTE;
const ROUTE_ROLES = import.meta.env.VITE_ROLES_ROUTE;
const ROUTE_STORAGE = import.meta.env.VITE_STORAGE_ROUTE;
const ROUTE_STOCK = import.meta.env.VITE_STOCK_ROUTE;
const ROUTE_PRODUCT = import.meta.env.VITE_PRODUCT_ROUTE;
const ROUTE_LOCATION = import.meta.env.VITE_LOCATION_ROUTE;
const ROUTE_MANAGER = import.meta.env.VITE_MANAGER_ROUTE;
const ROUTE_DELIVERY = import.meta.env.VITE_DELIVERY_ROUTE;
const ROUTE_DISPATCHER = import.meta.env.VITE_DISPATCHER_ROUTE;
const ROUTE_PRVIDER = import.meta.env.VITE_PROVIDER_ROUTE;
const ROUTE_ORDERS = import.meta.env.VITE_ORDER_ROUTE;
const BUSINESS_ROUTE = import.meta.env.VITE_BUSINESS_ROUTE;
const ROUTE_STOCK_TRANSACTION = import.meta.env.VITE_STOCK_TRANSACTIONS_ROUTE;
const SERVER_GEOLOCALIZATION_IP = import.meta.env.VITE_DEV_GEO_URL;
const ROUTE_GEOLOCALIZATION = import.meta.env.VITE_GEOLOCALIZATION_ROUTE;
const ROUTE_MAPDELIVERIES = import.meta.env.VITE_MAPDELIVERIES_ROUTE;
const SERVER_REPORTS_IP = import.meta.env.VITE_DEV_REPORTS_URL;
const ROUTE_REPORTS = import.meta.env.VITE_REPORTS_ROUTE;

export const ENV = {
    BASE_PATH: SERVER_IP,
    BASE_API_AUTH_USERS: `${SERVER_IP}${AUTH_ROUTE}${ROUTE_USERS}`,
    BASE_API_UTILITIES: `${SERVER_IP}${AUTH_ROUTE}${ROUTE_UTILITIES}`,
    BASE_API_ROLES: `${SERVER_IP}${AUTH_ROUTE}${ROUTE_ROLES}`,
    API_ROUTES: {
        SIGNIN: '/SignIn',
        SIGNUP: '/SignUp',
        RESENDCODE: '/resendVerifyCode',
        RESEND2FACODE: '/resend2FACode',
        VERIFYCODE: '/VerifyCode',
        VERIFY2FACODE: '/Verify2FACode',
        SENDFORGOTPASSWORD: '/SendForgotPassword',
        SENDRESETPASSWORD: '/SendResetPassword',
        RESTOREPASSWORD: '/ResetPassword',
        FORGOTPASSWORD: '/ForgotPassword',
        GETUSERBYID: '/GetUserById/:id',
        GETALLUSERS: '/GetAllUsers',
        GETALLDEPARTMENTS: '/departments/getAll',
        GETCITIESBYDEPARTMENT: '/cities/:department',
        CREATEROL: '/Create',
        UPDATEROL: '/Update',
        DELETEROL: '/Delete',
        GETALLROLES: '/GetAll',
        CREATEUSER: '',
        DELETEUSER: '/DeleteUser/',
    },

    BASE_PATH_INVENTORY: SERVER_INVENTORY_IP,
    BASE_PATH_INVEN_STORAGE: `${SERVER_INVENTORY_IP}${INVENTORY_ROUTE}${ROUTE_STORAGE}`,
    BASE_PATH_INVEN_STOCK: `${SERVER_INVENTORY_IP}${INVENTORY_ROUTE}${ROUTE_STOCK}`,
    BASE_PATH_INVEN_PRODUCT: `${SERVER_INVENTORY_IP}${INVENTORY_ROUTE}${ROUTE_PRODUCT}`,
    API_ROUTES_INVENTORY: {
        GETALLSTORAGES: '/GetAll',
        CREATEASTORAGE: '/create',
        GETSTORAGESWITHPRODUCTS: '/withProducts/',
        GETSTORAGEBYID: '/getById/:id',
        GETSTOCKBYSTORAGE: '/stock/',
        VERIFYAMOUTNTOFPRODUCT: '/verify-stock/',
    },
    API_ROUTES_INVENTORY_PRODUCT: {
        GETALLPRODUCTS: '/GetAll',
        CREATEPRODUCT: '/create',
        UPDATEPRODUCT: '/update',
        DELETEPRODUCT: '/delete',
        GETPRODUCTSBYSTORAGE: '/getProductsByStorage/',
    },

    BASE_API_GEOLOCALIZATION: `${SERVER_GEOLOCALIZATION_IP}${ROUTE_GEOLOCALIZATION}`,
    BASE_API_MAPDELIVERIES: `${SERVER_GEOLOCALIZATION_IP}${ROUTE_GEOLOCALIZATION}${ROUTE_MAPDELIVERIES}`,
    API_ROUTES_GEOLOCALIZATION_MAPDELIVERIES: {
        UPDATDELIVERYLOCATION: '/updateDeliveryLocation',
        GETDELIVERYLOCATION: '/getDeliveryLocation/',
    },

    BASE_PATH_BUSINESS: SERVER_BUSINESS_IP,
    BASE_PATH_BUSINESS_LOCATION: `${SERVER_BUSINESS_IP}${BUSINESS_ROUTE}${ROUTE_LOCATION}`,
    BASE_PATH_BUSINESS_MANAGER: `${SERVER_BUSINESS_IP}${BUSINESS_ROUTE}${ROUTE_MANAGER}`,
    BASE_PATH_BUSINESS_DELIVERY: `${SERVER_BUSINESS_IP}${BUSINESS_ROUTE}${ROUTE_DELIVERY}`,
    BASE_PATH_BUSINESS_DISPATCHER: `${SERVER_BUSINESS_IP}${BUSINESS_ROUTE}${ROUTE_DISPATCHER}`,
    BASE_PATH_BUSINESS_PROVIDER: `${SERVER_BUSINESS_IP}${BUSINESS_ROUTE}${ROUTE_PRVIDER}`,
    BASE_PATH_BUSINESS_ORDERS: `${SERVER_BUSINESS_IP}${BUSINESS_ROUTE}${ROUTE_ORDERS}`,
    BASE_PATH_STOCK_TRANSACTION: `${SERVER_BUSINESS_IP}${BUSINESS_ROUTE}${ROUTE_STOCK_TRANSACTION}`,
    API_ROUTES_BUSINESS: {
        //LOCATION
        GETALLLOCATIONS: '/get',
        //MANAGER
        GETMANAGERS: '/get',
        GETMANAGERBYUSERID: '/getManagerByUserId/',
        DELETEMANAGER: '/delete',
        GETSTORAGEBYMANAGER: '/getStorageByManagerId/',
        //DELIBERY
        GETDELIVERIES: '/get',
        CREATEDELIVERY: '/create',
        DELETEDELIVERY: '/delete',
        GETDELIVERYBYUSERID: '/getUserId/',
        //DISPATCHER
        DELETEDISPATCHER: '/delete',
        GETDISPATCHERBYUSERID: '/getByUserId/',
        //STOCK
        GETSTOCKBYDISPATCHER: '/getStock/',
        GETALLSTOCKTRANSACTIONS: '/get',
        //ORDERS
        GETALLORDERS: '/getAll',
        GETORDERSBYDISPATCHER: '/getOrdersByDispatcherId/',
        GETORDERSBYSTORAGE: '/getOrdersByStorageId/',
        GETORDERWITHDELIVERY: '/getOrderWithDelivery/',
        GETORDERSBYDELIVERY: '/getOrderByDeliveryId/',
        GETORDERBYNUMBER: '/get/',
        CREATEAORDER:'/create',
        UPDATEORDERSTATE: '/changeOrderState/',
        //STORAGE
        GETSTORAGEBYMANAGER: '/getStorageByManagerId/',
        GETSTORAGEBYORDERID: '/getOrderStorage/',
    },
    BASE_PATH_REPORTS: `${SERVER_REPORTS_IP}${ROUTE_REPORTS}`,
    API_ROUTES_REPORTS: {
        GETDELIVEREDORDERSBYDELIVERY: '/delivery/',
        GETDELIVEREDORDERS : '/all/',
    }

}

export const ROLES = {
    SUPERADMIN: 'SUPERADMIN',
    MANAGER: 'MANAGER',
    DISPATCHER: 'DISPATCHER',
    DELIVERY: 'DELIVERY',
    GUEST: 'GUEST'
}