const SERVER_IP = import.meta.env.VITE_DEV_AUTH_URL;
const SERVER_BUSSINESS_IP = import.meta.env.VITE_DEV_BUS_URL;
const SERVER_INVENTORY_IP = import.meta.env.VITE_DEV_INVEN_URL;
const AUTH_ROUTE = import.meta.env.VITE_AUTH_ROUTE;
const INVENTORY_ROUTE = import.meta.env.VITE_INVENTORY_ROUTE;
const ROUTE_USERS = import.meta.env.VITE_USERS_ROUTE;
const ROUTE_UTILITIES = import.meta.env.VITE_UTILITIES_ROUTE;
const ROUTE_ROLES = import.meta.env.VITE_ROLES_ROUTE;
const ROUTE_STORAGE = import.meta.env.VITE_STORAGE_ROUTE;
const ROUTE_STOCK = import.meta.env.VITE_STOCK_ROUTE;
const ROUTE_PRODUCT = import.meta.env.VITE_PRODUCT_ROUTE;
const ROUTE_LOCATION = import.meta.env.VITE_LOCATION_ROUTE;
const ROUTE_MANAGER = import.meta.env.VITE_MANAGER_ROUTE;
const ROUTE_DELIVERY = import.meta.env.VITE_DELIVERY_ROUTE;
const ROUTE_DISPATCHER = import.meta.env.VITE_DISPATCHER_ROUTE;
const ROUTE_PRVIDER = import.meta.env.VITE_PROVIDER_ROUTE;
const ROUTE_ORDERS = import.meta.env.VITE_ORDER_ROUTE;

export const ENV ={
    BASE_PATH: SERVER_IP,
    BASE_API_AUTH_USERS: `${SERVER_IP}${AUTH_ROUTE}${ROUTE_USERS}`,
    BASE_API_UTILITIES: `${SERVER_IP}${AUTH_ROUTE}${ROUTE_UTILITIES}`,
    BASE_API_ROLES: `${SERVER_IP}${AUTH_ROUTE}${ROUTE_ROLES}`,
    API_ROUTES:{
        SIGNIN: '/SignIn',
        SIGNUP: '/SignUp',
        RESENDCODE: '/resendVerifyCode',
        RESEND2FACODE: '/resend2FACode',
        VERIFYCODE: '/VerifyCode',
        VERIFY2FACODE: '/Verify2FACode',
        SENDFORGOTPASSWORD: '/SendForgotPassword',
        SENDRESETPASSWORD: '/SendResetPassword',
        RESTOREPASSWORD: '/ResetPassword',
        FORGOTPASSWORD: '/ForgotPassword',
        GETUSERBYID:  '/GetUserById/:id',
        GETALLUSERS: '/GetAllUsers',
        GETALLDEPARTMENTS: '/departments/getAll',
        GETCITIESBYDEPARTMENT: '/cities/:department',
        CREATEROL : '/Create',
        UPDATEROL : '/Update',
        DELETEROL: '/Delete',
        GETALLROLES: '/GetAll',
        CREATEUSER: '/',
        DELETEUSER: '/:id',
    },

    BASE_PATH_INVENTORY: SERVER_INVENTORY_IP,
    BASE_PATH_INVEN_STORAGE: `${SERVER_INVENTORY_IP}${INVENTORY_ROUTE}${ROUTE_STORAGE}`,
    BASE_PATH_INVEN_STOCK: `${SERVER_INVENTORY_IP}${INVENTORY_ROUTE}${ROUTE_STOCK}`,
    BASE_PATH_INVEN_PRODUCT: `${SERVER_INVENTORY_IP}${INVENTORY_ROUTE}${ROUTE_PRODUCT}`,
    API_ROUTES_INVENTORY:{
        GETALLSTORAGES: '/GetAll',
    },

    BASE_PATH_BUSSINESS: SERVER_BUSSINESS_IP,
    BASE_PATH_BUSSINESS_LOCATION: `${SERVER_BUSSINESS_IP}${ROUTE_LOCATION}`,
    BASE_PATH_BUSSINESS_MANAGER: `${SERVER_BUSSINESS_IP}${ROUTE_MANAGER}`,
    BASE_PATH_BUSSINESS_DELIVERY: `${SERVER_BUSSINESS_IP}${ROUTE_DELIVERY}`,
    BASE_PATH_BUSSINESS_DISPATCHER: `${SERVER_BUSSINESS_IP}${ROUTE_DISPATCHER}`,
    BASE_PATH_BUSSINESS_PROVIDER: `${SERVER_BUSSINESS_IP}${ROUTE_PRVIDER}`,
    BASE_PATH_BUSSINESS_ORDERS: `${SERVER_BUSSINESS_IP}${ROUTE_ORDERS}`,
    API_ROUTES_BUSSINESS:{
        GETALLLOCATIONS: '/GetAll',
        GETALLMANAGERS: '/GetAll',
        GETALLDELIVERY: '/GetAll',
        GETALLDISPATCHER: '/GetAll',
        GETALLPROVIDERS: '/GetAll',
        GETALLORDERS: '/GetAll',
    }
}

export const ROLES = { 
    SUPERADMIN: 'SUPERADMIN',
    MANAGER: 'MANAGER',
    DISPATCHER: 'DISPATCHER',    
    DELIVERY: 'DELIVERY',
    GUEST: 'GUEST'
}